### ISSUE TITLE
usability observations

### ISSUE THREAD

**Issue by jans23** [saturneric/GpgFrontend#100]
From testing GpgFrontend I observed the following glitches. Giving it as feedback to get fixed potentially:

Double clicking a PDF or an encrypted .pgp file opens it and shows it's binary content. This isn't helpful. Instead I would expect the .gpg file to be decrypted and the PDF to be opened in system's PDF viewer.

On the right panel which shows the keys: Sorting keys alphabetically is not possible. Clicking on the columns' title doesn't change the order. Also searching for keys isn't possible which would be helpful in my case, where I have hundreds of keys in my keyring.

**Comment by saturneric** [comment]
This feature is now supported and will be introduced in the upcoming 2.1.1 version.
