### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by Hub-O-Gits** [saturneric/GpgFrontend#101]
What are they?
Please post them in a prominent place.

**Comment by saturneric** [comment]
Added in manual.

**Comment by Hub-O-Gits** [comment]
Thank you, but I couldn't find any mention of system requirements (compatible OS versions, and any app-related dependencies) at https://www.gpgfrontend.bktus.com/overview - neither at the top, nor in the left-side index.
The last change to "manual" here was 3 months ago, so perhaps that's why.
Including them in the manual certainly makes sense, but the user would have to go dig for it. So it would be ideal to also list them near the top of README.md, since it's essential for the user to obtain that info up front.
