### ISSUE TITLE
Building from source broke my system

### ISSUE THREAD

**Issue by 0xblur** [saturneric/GpgFrontend#111]
Hi, I'm using Arch, btw. I didn't know there was an `.AppImage` of this program. I found it through the AUR. I tried building the latest version and It froze my system during make (or make install?). I rebooted my laptop during the process. Now I can't log in to my user (root still works). I'm returned to login every time. Any idea why this could be happening?

**Comment by saturneric** [comment]
I remembered that the compile and install configuration will not change the ```.profile``` file. Does anything else wrong?

**Comment by saturneric** [comment]
I apologize for any confusion, but I am not the maintainer of the AUR package. You may want to refer to the maintainer mentioned in issue #98 for assistance.
