### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by gammexane** [saturneric/GpgFrontend#113]
Hello, I just found this fantastic piece of software, this is by far the best GPG client I have used since the old Seahorse version (like 20 years ago). 
The question is, will you please create a Flatpak? It would be easy to update and a lot of more ppl could find it. 
In fact I was searching for GPG in Flathub and I only found 3 packages and they are only keyrings, they don't have all the features GpgFrontend has.

Thanks for this client, it is amazing.

Btw, do you know this WKD https://keys.mailvelope.com/? If you could add it to the list of servers would be great.

**Comment by saturneric** [comment]
Thank you for your support. Prior to your mention, I hadn't considered Flatpak, but I will look into it now and consider publishing there. Regarding the Key Server you mentioned, I will evaluate it and add it to the list if appropriate.

**Comment by gammexane** [comment]
Fatpak is fantastic. Check it. 
And the WKD, it was the only one that check my email when I upload my key... Ofc, open source and so on.

As I said, fantastic application, I will be around spreading the good news, I can help translating it into spanish if you need.

**Comment by saturneric** [comment]
Thank you so much for your kind words! It's truly inspiring to hear such positive feedback. Your support means a lot to us.

Regarding the translation, at the moment the most convenient method is to modify the corresponding [.po files](https://github.com/saturneric/GpgFrontend/blob/main/resource/lfs/locale/po/es_ES.po) and then send them to me via email. While online platforms like Crowdin are great, I currently don't have the bandwidth to maintain them.

Thank you again for your willingness to help and spread the word about our application!

**Comment by gammexane** [comment]
No, thank you! this piece of software has just entered the ranking of my top 5 most used. I will spread the word, in fact I am already doing it. I am going to help you with the translation as soon as I have some free time.

**Comment by speendo** [comment]
I want to support the suggestion to release a flatpak version!

**Comment by saturneric** [comment]
Works were almost done, and I have submitted a PR to Flathub. Hope it works!

https://github.com/flathub/flathub/pull/4608

**Comment by saturneric** [comment]
> Hello, I just found this fantastic piece of software, this is by far the best GPG client I have used since the old Seahorse version (like 20 years ago). The question is, will you please create a Flatpak? It would be easy to update and a lot of more ppl could find it. In fact I was searching for GPG in Flathub and I only found 3 packages and they are only keyrings, they don't have all the features GpgFrontend has.
> 
> Thanks for this client, it is amazing.
> 
> Btw, do you know this WKD https://keys.mailvelope.com/? If you could add it to the list of servers would be great.

/, you can add [it](https://keys.mailvelope.com) to the server list by yourself. I will verify it and add it to the default server list later.

**Comment by saturneric** [comment]
Things are all done. You can gain this application later on [Flathub](https://flathub.org/apps/com.bktus.gpgfrontend).
