### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ndekross** [saturneric/GpgFrontend#114]
Hello, I was wondering if there are any plans to include a dark mode feature in the future. Thank you.

**Comment by saturneric** [comment]
May I inquire about your operating system? Dark mode can be automatically enabled on macOS.

**Comment by ndekross** [comment]
It's Windows 11

**Comment by saturneric** [comment]
Okay. It's not difficult to add it. I'll work on it.

**Comment by saturneric** [comment]
Supported at v2.1.2.
