### ISSUE TITLE
Allow specifying which key or passphrase to use to decrypt

### ISSUE THREAD

**Issue by samtuke** [saturneric/GpgFrontend#118]
When I try to open a GPG CLI encrypted file in GpgFrontend, no key or passphrase is requested and decryption always fails. I don't mind whether I use symmetric or asymmetric encryption in my use case, but in either case, GpgFrontend must know what key or passphrase to use. So why doesn't it request it? I don't see a way to specify either of these before attempting decryption in the GUI. Thanks.

**Comment by saturneric** [comment]
You may not the only person who has this question. When I wrote this function in 2021, I had this question that why gpgme decryption function didn't need me provide the specific key which will the decrypting operation. Finally, I realized that gpg itself would find the exact key for the encrypted texts as well as files, or it will require you to provide the passphrase for symmetric encrypted texts. Therefore, for your question, It appears that you don't have the proper key in your database.
