### ISSUE TITLE
during verification "A Signature Not Fully Valid. (May used a subkey to sign)"

### ISSUE THREAD

**Issue by marcof333** [saturneric/GpgFrontend#120]
In "Computer A", I generate a keypair and I export the" Public key A" as .asc. I use the "Private key A" to sign the doc that I encrypt for "Computer B" (whose "Public key B" was previously imported in ComputerA as .asc).
Now in Computer B I import the" Public key A" as .asc. And I decrypt&verify the document above.
I got this error message "A Signature Not Fully Valid. (May used a subkey to sign)"

here below the full message.
thanks.

[#] Verify Operation [Success]
------------>
[>] Signed On(UTC) 2023-11-01T22:31:10

[>] Signatures List:
Signature [1]:
A Signature Not Fully Valid.
(May used a subkey to sign)
    Signed By: [omitted xxxxxxxxxxxxxx]
    Public Key Algo: RSA
    Hash Algo: SHA1
    Date(UTC): 2023-11-01T22:31:10

<------------

**Comment by saturneric** [comment]
From what you've described, it appears that the setup was done correctly. However, the error message "A Signature Not Fully Valid. (May used a subkey to sign)" can indeed be confusing. Let me offer some clarification to help resolve this issue.

One key aspect to check is the Trust Level of the public key on Computer B, especially for the key imported from Computer A. The trust level plays a crucial role in the verification process. If it's not appropriately set, it can lead to verification errors. To adjust this:

1. Navigate to either "Keybox Tool" or "KeyPair Management".
2. Right-click on the key in question.
3. Select "Set Owner Trust Level".
4. If you're confident about the trustworthiness of the public key you've imported, choose "Ultimate" as the trust level.

<img width="476" alt="image" src="https://github.com/saturneric/GpgFrontend/assets/20257134/87749f93-a663-48c4-a00e-42f9ebe31c06">

 
The operations above may work as I tested it.

I understand that the information displayed can be confusing, and I assure you that we will work on making it clearer in future updates. I appreciate your patience and are grateful for your use of our software.

**Comment by saturneric** [comment]
Okay. It's nice to hear that.

**Comment by saturneric** [comment]
> By the way I take this occasion to highlight you that I have a different graphical interface compare to your screenshot, I attache a pdf with some screenshots.

I forgot that I was using an under-developing version which hasn't released yet. ;)
