### ISSUE TITLE
Improve the "File Browser" functionality

### ISSUE THREAD

**Issue by marcof333** [saturneric/GpgFrontend#121]
1. bug: in Win,  when I click on "File Browser", in the path box I can see only the volume of the folder where the FrontendGPG.exe is stored. To change the volume, e.g. to select a file that is in a USB key, I have to manually digit the path, e.g.  "e:/file...."

2. improvement: If I click on the button "Open", a windows to select the file is popping up with the usual intuitive aspect; selecting the desired file it's opening in the textual box of the GpgFrontend tool and everything is working fine.
On the other side if I click on the button "File Browser", I have to navigate by the path box texting the target path of the file to be decrypted, or using the very small arrow on the very right of the path box... too nerd :)
Suggestion: use the same interface to select the file as already applied in the command behind the button "Open".

**Comment by saturneric** [comment]
Currently, you will need to select a directory before entering into the File Browser. So this situation has been improved. ba7dd4e
