### ISSUE TITLE
Missing packages in ubuntu/debian installation instructions

### ISSUE THREAD

**Issue by exaexa** [saturneric/GpgFrontend#124]
Hello,

it might be good to add extra packages to the ubuntu apt-get commands in the compiling instructions. I needed the following extra ones:

- qt6-base-dev
- libqt6core5compat6-dev
- libgpgme-dev

I'll try to verify this on a clean ubuntu/debian install asap and let you know if there's anything other required.

Thanks!
-mk

**Comment by saturneric** [comment]
Thank you for your help! I'll work on it later.

**Comment by saturneric** [comment]
README.md updated. fd1f245ebb

**Comment by exaexa** [comment]
Thanks!
