### ISSUE TITLE
Is there a way to specify the data directory?

### ISSUE THREAD

**Issue by FloraMaeWolfe** [saturneric/GpgFrontend#125]
Is there a way to specify the data directory?

Example, the windows "portable" zip puts the data in the usual place which is not really portable. Is there a command line option or other method to specify the location of the data directory?

I'm also curious for Linux too.

**Comment by saturneric** [comment]
Unfortunately, not yet. But I''ve just added a function that can switch data and config path to a relative path at start. I call it PROTABLE mode. Enable it just by placing an empty file named "PROTABLE.txt" under the directory where the binary executable of GpgFrontend located. 

Any advice?

**Comment by saturneric** [comment]
This portable mode is added to the current develop source code. It will take effect at v2.1.2. 36509c76e

> Unfortunately, not yet. But I''ve just added a function that can switch data and config path to a relative path at start. I call it PORTABLE mode. Enable it just by placing an empty file named "PORTABLE.txt" under the directory where the binary executable of GpgFrontend located.
> 
> Any advice?
