### ISSUE TITLE
[ENHANCEMENT] Add darkmode for linux such as GTK theme support or an internal toggle

### ISSUE THREAD

**Issue by NanashiTheNameless** [saturneric/GpgFrontend#133]
Add darkmode for linux such as GTK theme support or an internal toggle
i saw windows support was added but discovered the linux support was lackluster...

**Comment by saturneric** [comment]
For flatpak distribution, by using Ubuntu 20.04, I can see that the darkmode works on v2.1.3 as I set the system theme to dark. 

I'm now wondering if this issue has already solved.
