### ISSUE TITLE
English not listed!

### ISSUE THREAD

**Issue by lah0t** [saturneric/GpgFrontend#135]
in lnaguage drop-down list there isn't English listed.
so you just get English UI when your locale setting for whole system set to English.

**Comment by LuKtdf** [comment]
Hello same issue here.
You can try to edit the preference file to change the lang to english (en_EN).
On MacOS this file is ~/Library/Preferences/com.bktus.gpgfrontend.GpgFrontend.plist
(don't forget to clear preferences cache with "killall -u yourusername cfprefsd")

I don't know about windows or linux

**Comment by saturneric** [comment]
Should it be required, please feel free to share the operating system you are currently using with me. I would be more than happy to provide you with a binary build specifically tailored to circumvent this issue.

**Comment by saturneric** [comment]
https://drive.google.com/drive/folders/1O4NuKbX4LNNhFVmMpD_Wqls4wqJ0TglG?usp=sharing

Here it is. I hope this version addresses your needs effectively. However, please proceed with caution as this is an under-development version and has not been officially released yet.

**Comment by saturneric** [comment]
Got, I will fix it at v2.1.3.
