### ISSUE TITLE
Windows: Make the app stop using user\appdata\roaming\gnupg folder

### ISSUE THREAD

**Issue by Searinox** [saturneric/GpgFrontend#138]
I am attempting a private setup that involves everything stored in a special container and pretty much cannot trust anything outside that location, hence why I went for the portable version. That the app decides to still use the user gnupg folder within the user profile folder - AND for key storage of all things - is not something I can accept. Is there a way to stop this behavior?

**Comment by saturneric** [comment]
In your private setup, it's understandable that you require all data to be stored securely within a specific container. To address your concern regarding the default key storage location used by the app, I would like to inform you that within the GnuPG Controller, there is an option to specify an alternative location for the key database. This functionality should allow you to direct key storage to a location of your choosing, aligning with your need for a self-contained environment. I recommend giving this a try to customize the key storage path to your preferred secure container.
