### ISSUE TITLE
Cannot import keys issued in Kleopatra

### ISSUE THREAD

**Issue by rhaley-starfish** [saturneric/GpgFrontend#139]
I generated keys using Kleopatra on Windows 11 and when I attempt to import them into GpgFrontend on a Mac, I get the error "There are no keys to import." (Paraphrased, I didn't write it down)

I tried modifying the keyfile to use the Mac line ending (CR instead of CRLF) but it did not fix the issue. 

I generated a second keyset set for testing and to share in this issue. Again, GpgFronend gave me an error when I tried to import them. I then went to the command line and imported the testing keypair through gpg. I closed and re-opened GpgFrontend and now they are loaded. I then go to import, and now GpgFrontend will import the original keys that were being rejected. I have included the test keys. The password is "testing".

[Testy Testerson_0x74F67C70_public.asc.txt](https://github.com/saturneric/GpgFrontend/files/14528087/Testy.Testerson_0x74F67C70_public.asc.txt)
[Testy Testerson_0x74F67C70_SECRET.asc.txt](https://github.com/saturneric/GpgFrontend/files/14528088/Testy.Testerson_0x74F67C70_SECRET.asc.txt)

**Comment by saturneric** [comment]
<img width="1283" alt="image" src="https://github.com/saturneric/GpgFrontend/assets/20257134/aa6ee842-1884-4d3c-992e-9a57c27ea62c">

I'd tested the public and private keys which you had given. There are all imported successfully at my machine at v2.1.2.
I will continue to track this issue. If you have any discover, feel free to report it under this issue.

**Comment by rhaley-starfish** [comment]
Weird. Thanks for checking into it. I have what I need working and probably won't be looking back at this. All my future keys will be generated on the Mac with GpgFrontend. Cheers!
