### ISSUE TITLE
Fix permalinks

### ISSUE THREAD

**Issue by jermanuts** [saturneric/GpgFrontend#142]
if you visit https://www.gpgfrontend.bktus.com/?id=work-offline you will be greeted with 
![image](https://github.com/saturneric/GpgFrontend/assets/109705802/96ea3a84-ba8b-4551-988a-56776d116200)

Also when clicking on the logo to visit the Homepage https://gpgfrontend.bktus.com/index.html the page is blank.

Perhaps you can switch to a better static documentation generator? https://starlight.astro.build/ ?

**Comment by saturneric** [comment]
A good suggestion. I will carefully look into it.

**Comment by saturneric** [comment]
https://github.com/saturneric/GpgFrontend-Manual
As you wish. :)

**Comment by jermanuts** [comment]
Amazing 🚀

**Comment by jermanuts** [comment]
Will the manual/docs site be removed from main repo?
