### ISSUE TITLE
ERROR: Inappropriate ioctl for device when using yubikey

### ISSUE THREAD

**Issue by creamlike1024** [saturneric/GpgFrontend#144]
<img width="503" alt="截屏2024-03-25 17 54 49" src="https://github.com/saturneric/GpgFrontend/assets/25699126/95a64af7-8c3e-4849-b46d-7662c283c761">

System: macOS 14.4 (x86)
Version: 2.1.2 (Installed through brew)

Using gpg from terminal with yubikey has no problem.

Should I need to make certain settings?

**Comment by saturneric** [comment]
在GnuPG控制面板中勾选”用Pinentry...“那一项试试。
然后，如果还是不行的话，可以结合下面这个stack看看：
https://stackoverflow.com/questions/51504367/gpg-agent-forwarding-inappropriate-ioctl-for-device

**Comment by creamlike1024** [comment]
```
brew install pinentry-mac
echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" > ~/.gnupg/gpg-agent.conf
```
