### ISSUE TITLE
Dark mode not working in Flatpak version in MX Linux XFCE

### ISSUE THREAD

**Issue by sang-shelton** [saturneric/GpgFrontend#147]
I installed the app via flatpak and the dark mode is not working.
It would be better to be able to toggle the Dark mode explicitly.
I am using MX Linux - xfce

**Comment by rafaone** [comment]
i have same problem.

**Comment by saturneric** [comment]
I forgot that Dark mode at v2.1.2 only supports Windows.

**Comment by saturneric** [comment]
So far, dark mode is working fine under Flatpak.

**Comment by sang-shelton** [comment]
Many times problems happen with flatpak apps i dont know why, like the dark mode is not working by default, i have to do it explicitly from the settings.

Another problem is that i cannot resize the window and cannot maximize it. There is part of the window that is going down the screen and not visible. 

deb packages seems to be working more correctly than flatpaks.
