### ISSUE TITLE
Flatpak maintenance

### ISSUE THREAD

**Issue by gammexane** [saturneric/GpgFrontend#149]
Hello, I have just installed Fedora 40 from scratch and ofc  I installed GpgFrontend, but after I install the flatpak I have the message "This app is no longer receiving updates" as you can see in the screenshot. I don't know if I missed something or it is just a "gnome software" error. 

![Screenshot from 2024-05-05 20-12-21](https://github.com/saturneric/GpgFrontend/assets/509348/6e9b71a6-91ab-485e-91d4-ed7589792267)

Cheers!

**Comment by saturneric** [comment]
Maybe a "gnome software" error. As I can see on the flathub, that's all right:

![image](https://github.com/saturneric/GpgFrontend/assets/20257134/2a440ab6-8c14-423a-8f14-47aa10c88366)

**Comment by gammexane** [comment]
That is what I thought but I wanted to confirm. Thank you very much. 
It is weird tho, i only have this problem with GpgFrontend.

![Screenshot from 2024-05-05 20-46-52](https://github.com/saturneric/GpgFrontend/assets/509348/0df496e7-77dd-422f-acd7-8cc929e5223d)

**Comment by gammexane** [comment]
I think the problem is in one of the libraries you are using... 

![image](https://github.com/saturneric/GpgFrontend/assets/509348/598acbfb-4b38-4ea5-8c73-f4240b01245f)

**Comment by saturneric** [comment]
Thanks for pointing out this. With the provided information, I found the origin: https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/fc23bc54ae22f5e17dbef556b37d842cfd7522d8

The branch 6.5 was marked as EOF about 2 weeks ago. And I'll switch to branch 6.6.
