### ISSUE TITLE
Portable.txt missing in 2.1.3 / windows

### ISSUE THREAD

**Issue by Achim16** [saturneric/GpgFrontend#150]
In contrast to 2.1.2 the Windows archives GpgFrontend-2.1.3-qt(x)-windows-x86_64-portable.zip do not contain Portable.txt
in path Program\bin.
In effect this setup of GPGFrontEnd is NOT portable then any longer, as it stores its config.ini and several folders then in users\(user)\appdata\local\gpgfrontend. 
Workaround is to copy a zero-byte portable.txt to the above folder.

**Comment by saturneric** [comment]
Sorry, I forgot the PORTABLE.txt. It has been added now.
