### ISSUE TITLE
Columns in Key Pair Management

### ISSUE THREAD

**Issue by Achim16** [saturneric/GpgFrontend#152]
Having many keys generated over time it would be very useful if a key's creation date would
be shown for the key listed in the key management window as a separate column, same is true for a key's 'comment' and algorithm.
Also, it'd useful if the key list sort order could be changed by clicking on the column header

Thanks

**Comment by saturneric** [comment]
After the commit 2c42d6cb, all these features mentioned above are fulfilled and will be available to users in version 2.1.4.
