### ISSUE TITLE
Language Setting not affecting Pinentry

### ISSUE THREAD

**Issue by Achim16** [saturneric/GpgFrontend#153]
On a W10 System (regional settings in German) I have successfully changed language settings to English.

Pinentry however displays its window in German. Can this be changed as well ? 

Edit - I should have been more specific, the above happens when GnuPG Controller setting 'Use Pinentry as Password Input' is active. Unchecked option enables 'bundled pinentry dialog', which is correctly in English

**Comment by saturneric** [comment]
Pinentry is a GnuPG component. Therefore, the language settings of GpgFrontend will not affect it.
