### ISSUE TITLE
Elgamal Keys

### ISSUE THREAD

**Issue by Achim16** [saturneric/GpgFrontend#154]
Good evening,

is there any reason why gpgfrontend does not support Elgamal (non-EC) in Keypair (DSA/Elgamal) nor Subykey ?

Thanks

**Comment by saturneric** [comment]
That's a case I didn't discover. 
Maybe you can import these keys (if gnupg supports them) but ,unfortunately, can not generate a new one with GpgFrontend for now.

I'll learn this case and try adding on the support of Elgamal.

**Comment by Achim16** [comment]
Thanks. GnuPG 2 definitely supports Elgamal, see option 2 on --full-generate-key.
(Sub)Keys are to my view also correctly imported and shown in GPGFrontend (Algorithm ELG-E, algorith detail eg ELG20248).
So it seems that only key generation is affected

**Comment by saturneric** [comment]
After the commit 12fdf94, all these features mentioned above are fulfilled and will be available to users in version 2.1.4.
