### ISSUE TITLE
GUI fails to launch on fedora 40 workstation and silverblue

### ISSUE THREAD

**Issue by Hxs2fJKjYZ** [saturneric/GpgFrontend#157]
I recently installed gpgfrontend flatpak on fedora 40 workstation and silverblue, but when I try to launch it, it shows as running in the background on Gnome, but the GUI doesn't launch. I have the same problem with the appimage version, both 2.1.3. I tried version 2.1.2 appimage and that one seems to launch without any issues.
This is a screenshot of the flatpak version run in terminal:
![Screenshot from 2024-06-14 15-01-04](https://github.com/saturneric/GpgFrontend/assets/12845068/9dcc015c-ca92-46ae-9733-6022cf7ab6dd)

Any help would be appreciated.

**Comment by saturneric** [comment]
You can try option `-l trace` or `-l debug`, and then more information will show.

**Comment by danruggi** [comment]
Same here, fedora 40, fresh install

![image](https://github.com/saturneric/GpgFrontend/assets/36973240/052d72fe-8027-4b43-862b-65bbf8f3360b)

**Comment by Hxs2fJKjYZ** [comment]
I don't know if it will help or not, but here is the output from running the appimage QT5 and QT6 version
![Screenshot from 2024-06-15 08-15-30](https://github.com/saturneric/GpgFrontend/assets/12845068/055a7368-85cf-42af-9eef-8ec46fc48016)

**Comment by saturneric** [comment]
I remember an anonymous user mentioning this to me, he said it was wayland having some issues with the flatpak environment again. I don't know if this is related, you guys could try disabling wayland and then theoretically the app will fallbak to x11 mode, if that works.

**Comment by saturneric** [comment]
Found something here: https://github.com/Ultimaker/Cura/issues/12776#issuecomment-1200127332

It appears that you can try this command for launch:
`GDK_BACKEND=x11 LD_PRELOAD=/usr/lib64/libstdc++.so.6 ./GpgFrontend.AppImage`

**Comment by Hxs2fJKjYZ** [comment]
I got flatpak version working, through a slightly different route. I disabled "Wayland windowing system" permission via flatseal, and it seems to work fine, although I haven't fully tested it yet.
![Screenshot from 2024-07-05 11-18-02](https://github.com/saturneric/GpgFrontend/assets/12845068/8738572d-420f-4569-ac4b-1852e168cda9)

**Comment by saturneric** [comment]
Eventually I found the problem and the fix is being released. it will be available on Falthub in 2-3 hours. You guys can recover the flatpak settings and continue to use wayland.

See: 8e70452cbedb5580161ca041f2d61bbd0cfa1524

Other than that, I also upgraded the Qt version to 6.7.
