### ISSUE TITLE
File encryption

### ISSUE THREAD

**Issue by Sue1133** [saturneric/GpgFrontend#159]
Hello. Could you add support for file encryption?

I opened the file, it opened as a bunch of characters, I encrypted them, and then tried to decrypt them and the file was broken. That is, now there is no file encryption function as such, as I understand it.

**Comment by saturneric** [comment]
https://www.gpgfrontend.bktus.com/guides/encrypt-decrypt-file/

Based on your description, would you see if this document is helpful? 

If there are problems with the functionality described in this document, feel free to continue to ask. :)

**Comment by Sue1133** [comment]
Yes, that's it, I wasn't paying attention, thank you.
