### ISSUE TITLE
Doesn't work with big enough files.

### ISSUE THREAD

**Issue by oracle1wr** [saturneric/GpgFrontend#16]
Hi,

I tried the app with image files and it doesn't work as expected. Just load a file, do encrypt, then decrypt and original file is broken. 
I tested with a picture, it doesn't work.
When I tried just simple text message typed right a way in the window, it works.

My OS is Ubuntu 18.04.

**Comment by saturneric** [comment]
Thanks, I will check it later.

**Comment by saturneric** [comment]
You cant open binary file like image. It won't work. Just right click the file and encrypt it.

**Comment by oracle1wr** [comment]
hm, yes tried built in file browser and using right click menu, encrypted and decrypted, it worked as expected.

Thanks
