### ISSUE TITLE
Valid Email Address Rejected with Error "Please provide an email address" on Outlook Email

### ISSUE THREAD

**Issue by NDGWIUD** [saturneric/GpgFrontend#167]
![image](https://github.com/user-attachments/assets/0b1941bf-b6d4-45f1-bf83-9e6c20f1c984)
![屏幕截图 2024-07-17 160851](https://github.com/user-attachments/assets/49b50957-4596-4908-91b0-176ede261f67)

**Comment by saturneric** [comment]
Email中是不区分大小写的，所以默认用小写即可。
