### ISSUE TITLE
GppGFrontend

### ISSUE THREAD

**Issue by Sue1133** [saturneric/GpgFrontend#171]
The portable version of the program for Windows (qt5 and qt6) has an error in the folder name, namely GppgFrontend:
![pic1](https://github.com/user-attachments/assets/abc7339c-cc19-4fc2-b23e-cdeb6a94c57a)
![pic2](https://github.com/user-attachments/assets/aaa9ebf7-2be9-4e16-a8bd-b6d77039a175)
This error was also in the previous version.

**Comment by saturneric** [comment]
v2.1.4.3 has been released and this issue has been fixed. You can download and use v2.1.4.3 if you feel the need.
