### ISSUE TITLE
GPGfrontend Mac OS Version 14.6.1 (23G93) crashing

### ISSUE THREAD

**Issue by jpalcantara** [saturneric/GpgFrontend#173]
Hello,

  I installed the latest version of GPGfrontend via brew and the application crashes.  I am running a MACBOOK AIR M1
  
  here is some of the details info:
  
  Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000003a10
Exception Codes:       0x0000000000000001, 0x0000000000003a10

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [6777]

VM Region Info: 0x3a10 is not in any region.  Bytes before following region: 4308338160
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100cc4000-100fb8000    [ 3024K] r-x/r-x SM=COW  /Applications/GpgFrontend.app/Contents/MacOS/GpgFrontend

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtCore                        	       0x103e41b0c QJsonDocument::isArray() const + 8
1   libgpgfrontend_core.dylib     	       0x1017d4080 0x1017c0000 + 82048
2   libgpgfrontend_core.dylib     	       0x1017d3f6c 0x1017c0000 + 81772
3   libgpgfrontend_core.dylib     	       0x1017d0d60 GpgFrontend::CacheManager::CacheManager(int) + 56
4   libgpgfrontend_core.dylib     	       0x101817980 0x1017c0000 + 358784
5   libgpgfrontend_core.dylib     	       0x1018178b4 GpgFrontend::CacheObject::CacheObject(QString) + 68
6   libgpgfrontend_core.dylib     	       0x101820fe4 GpgFrontend::GpgKeyTableProxyModel::slot_update_favorites() + 76
7   QtCore                        	       0x103e03530 0x103d34000 + 849200
8   libgpgfrontend_core.dylib     	       0x101820ef8 GpgFrontend::GpgKeyTableProxyModel::GpgKeyTableProxyModel(QSharedPointer<GpgFrontend::GpgKeyTableModel>, GpgFrontend::GpgKeyTableDisplayMode, GpgFrontend::GpgKeyTableColumn, std::__1::function<bool (GpgFrontend::GpgKey const&)>, QObject*) + 424
9   libgpgfrontend_ui.dylib       	       0x101617fb4 0x10155c000 + 769972
10  libgpgfrontend_ui.dylib       	       0x1016140a4 0x10155c000 + 753828
11  libgpgfrontend_ui.dylib       	       0x1016024d8 0x10155c000 + 681176
12  libgpgfrontend_ui.dylib       	       0x1015dbf58 0x10155c000 + 524120
13  libgpgfrontend_ui.dylib       	       0x10157656c GpgFrontend::UI::RunGpgFrontendUI(QApplication*) + 276
14  GpgFrontend                   	       0x100ccef54 0x100cc4000 + 44884
15  GpgFrontend                   	       0x100cd1e20 0x100cc4000 + 56864
16  dyld                          	       0x1870a3154 start + 2476

**Comment by saturneric** [comment]
Fixed, refer: 508526cb5cbaaa2dacd68fd23bb21fa8a3cbe74e

It may be a while before this fix is released.

**Comment by jpalcantara** [comment]
OK, it's too bad!  Will wait!
