### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by Eternal9100** [saturneric/GpgFrontend#176]
I am unable to resize the the window or view the whole UI in other than maximised view with 768 V.res in Windows Qt6 version and Appimage Qt6. The screenshot is as small as it can be made with the corner handle. Note toolbar moved to the right for desmonstation purposes. Otherwise coming on very nicely.

Using Windows 10 and Mint 22 Cinnamon.

E9100

![gpgfrontend](https://github.com/user-attachments/assets/c6e0f671-61c9-4612-96bb-0d85fd9c6c5c)

**Comment by saturneric** [comment]
fixed at d82bbd6eb479770bea7a20f6f9375791fc8ed1fa
