### ISSUE TITLE
Updates On Winget

### ISSUE THREAD

**Issue by Eternal9100** [saturneric/GpgFrontend#182]
Please consider updating released on Winget. The current version seems to be v2.1.3:

> C:\WINDOWS\system32>winget search gpgfrontend
Name                                                             Id                     Version Source
--------------------------------------------------------------------------------------------------------
GpgFrontend - OpenPGP/GnuPG crypto, sign and key management Tool 9NH716MQK2B5           Unknown msstore
GpgFrontend                                                      Saturneric.GpgFrontend 2.1.3   winget

This is a useful alternative for Kleopatra where Kde don't seem to be doing Win builds any longer.

**Comment by saturneric** [comment]
Have updated to v2.1.6 on winget. 

Refer: https://github.com/microsoft/winget-pkgs/pull/198852
