### ISSUE TITLE
Seg Fault by uploading to KeyServer

### ISSUE THREAD

**Issue by noppelmax** [saturneric/GpgFrontend#24]
I use the recent version 'v1.3.1-beta.2'. I created a new key with RSA 4096bit and directly clicked on "upload to keyserver" -> Segmentation Fault.

Do you have any idea?

**Comment by noppelmax** [comment]
The latest non-beta version I could find on github was 'v1.2.2'. On this version it worked fine.

**Comment by saturneric** [comment]
Please use v1.2.2 instead. I'am working on v1.3.x. Hope 1.3.x stable version will comming soon.
