### ISSUE TITLE
Enhancement Feature Request: Add gpg-zip function to encrypt or sign files into an archive

### ISSUE THREAD

**Issue by newtype0** [saturneric/GpgFrontend#33]
I often have large groups of files in a folder that I would like to encrypt into an archive for easy and secure transport. 

Command line gpg-zip encrypts or signs files into a gpg-ized tar and recognizes several options to specify keys and the zip output path. It would be great to have this command visualized for professional users.

**Comment by saturneric** [comment]
Thanks, I will do that later.

**Comment by saturneric** [comment]
This feature will initially appear in 2.0.5 and will be refined in future releases.

**Comment by saturneric** [comment]
In the upcoming v2.0.5 you will be able to encrypt folders, and new features have been added to handle tar.gpg correctly.
