### ISSUE TITLE
Error while decrypt or verify files if encrypted or signed with himself

### ISSUE THREAD

**Issue by Plagouille** [saturneric/GpgFrontend#43]
Hi,

I got the last (2.3.4) GnuPG installed then I use the 2.0.4 portable version of GpgFrontend.

If I verify or decrypt files (ok with text) encrypted or signed with GpgFrontend I get an error :
```
[#] Decrypt Operation[Failed] No data

[#] Verify Operation [Failed] No data
[>] Could not find information that can be used for verification.
```

If I try to encrypt or verify with Kleopatra I have also an error.

If I encrypt or sign with kleopatra and then decrypt or verify with GpgFrontend it works fine. 

I asked a friend to check and I got the same.

Any idea ?

**Comment by Plagouille** [comment]
It seems to work with 2.0.3 !

**Comment by saturneric** [comment]
Hi, under Windows, there is a problem that binary format files cannot be decrypted or signed properly. If you use Windows, please cancel binary function in the ASCII option in the settings(General Tab->ASCII Mode->Check it on).

I'm sorry for the inconvenience this has caused you. I will fix this in the new version.

**Comment by Plagouille** [comment]
Hi,

I unchecked ASCII option and now it can decrypt but the files are corrupted. I had the same in 2.0.3.

**Comment by saturneric** [comment]
Thanks for bringing this to my attention with your feedback, I'll start working on fixing it in the near future. If you find any other problems, feel free to give me feedback, thanks!

**Comment by Plagouille** [comment]
You're welcome. As I would like to use your software to teach PGP encryption with my students do you have any idea when you would be able to fix it ? We are 5 teachers who would like to use in reallity.

**Comment by saturneric** [comment]
I'm urgently fixing this issue, so I plan to release 2.0.5 early, giving me 2 days to do so.

**Comment by saturneric** [comment]
I evaluated the workload and 2.0.5 involves a lot of new features, 2 days is probably impossible, but I can send you a separate emergency fix version (2.0.5b) with my signature, can you give me your email address and your OS version?

I will include the source code in the email.

**Comment by Plagouille** [comment]
We don't need it now, not before 2 weeks. Let me know if I can help you.

**Comment by saturneric** [comment]
I have solved this problem today. I've tested on Windows and Linux and this issue should not be showing up, so I'll close the issue. Next, we can contact by email(eric@bktus.com). So please send me an email so we can establish a communication channel.

I'm currently working on v2.0.5 and there are a lot of features that haven't been finished or tested. It may take some time. But if you need me to provide you with v2.0.5 in advance, I can provide you with a special edition. This special edition disables new features of v2.0.5 that have not yet been developed or tested, but are sufficient to function properly and demonstrate the main features of gpg.

I can provide you with this special release and its full source code by mail. Feel free to give me some suggestions to improve the ease of use of this software, or to point out some problems that I haven't found yet.
