### ISSUE TITLE
Please enable 'Discussion' for this repository.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [saturneric/GpgFrontend#44]
I want to ask questions, but am not certain of where to. 'http://docs.github.com/discussions' provides information.

**Comment by saturneric** [comment]
Well, this is really a place to give users a place to discuss general issues.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@SATURNERIC, I am thankful.
