### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by KDropZ** [saturneric/GpgFrontend#47]
I generated a keypair on my linux machine, exported it with passphrase and everything went fine. Made a testimport on my linux machine, all fine. But when I now try to import the gfe pack (through "key management"->"import key"->"keypackage") on my windows machine the keyfields are blank. Ofcourse I rebooted Windows and tried to start gpgfrontend as admin, no difference.
~
Image 1: import on linux machine
![image](https://user-images.githubusercontent.com/77630187/157538189-04533a25-25e6-464a-8f08-8f5368a36c3d.png)
~
Image 2: import on windows machine
![image](https://user-images.githubusercontent.com/77630187/157538313-96211b92-369d-4747-8f52-9bf064a081a5.png)
~

**Comment by saturneric** [comment]
Thanks for the feedback, I will test this issue recently.

**Comment by saturneric** [comment]
This bug is the same problem as #43 .This issue has been fixed in version 2.0.5.
