### ISSUE TITLE
Decrypting a PGP Message

### ISSUE THREAD

**Issue by KDropZ** [saturneric/GpgFrontend#48]
For testing purposes I created a test PGP-Pair(machine A). Exported the public key and imported it in gpgfrontend on a vm(machine B).
I encrypted a simple Text on machine A to plain text and not saved into a file, but when I try to decrypt the text on machine B I'm getting the error "No secret key". Which ofcourse is correct as I just imported the senders public key. 
How is the right procedure for this without sending my private key?

**Comment by saturneric** [comment]
Thank you for your support! You should use the public key for encryption, and then decryption must use the private key. So, when you decrypt a cipher text, if no private key exists, it will say "no private key".
The correct procedure is this: you distribute your public key and keep your private key locally for decryption.
