### ISSUE TITLE
macos retina还是糊的

### ISSUE THREAD

**Issue by fbion** [saturneric/GpgFrontend#51]
可以调用yubikey加解密吗

**Comment by saturneric** [comment]
可以的我现在就是用yubikey里的密钥签名，网上有教程。

**Comment by saturneric** [comment]
现在手头上有一台MBP，我这段时间测试一下

**Comment by fbion** [comment]
> 现在手头上有一台MBP，我这段时间测试一下。方便说一下什么是模糊的吗，是界面吗？
https://raw.githubusercontent.com/fbion/macos.safe/master/%E6%88%AA%E5%B1%8F2022-03-20%20%E4%B8%8A%E5%8D%8810.43.22.png
https://raw.githubusercontent.com/fbion/macos.safe/master/%E6%88%AA%E5%B1%8F2022-03-20%20%E4%B8%8A%E5%8D%8810.43.41.png

**Comment by saturneric** [comment]
很抱歉我一直未能复现该问题，原因是新款的macbook已经没有使用retina显示屏了。我手上的这台是2019款的macbook。我曾经做出过修复，但无法验证是否真的解决了，现在看来并没有解决。

**Comment by saturneric** [comment]
未来的版本将会采用Qt6，这个问题应该能得到解决。可能还需要你在版本发布后，验证一下。
