### ISSUE TITLE
Doesn't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by nicraMarcin** [saturneric/GpgFrontend#64]
It doesn't work on newest ubuntu 22.04 because Ubuntu has newest libraries:
```shell
$ ldd /usr/bin/GpgFrontend 
...
	libicui18n.so.66 => not found
	libicuuc.so.66 => not found
	libcrypto.so.1.1 => not found
...
```
libicui is libicuXXX.so.70.1, libcrypto is libcrypto.so.3

**Comment by saturneric** [comment]
This has to do with the versioning policy of the icu library (an internationalization support library). It binds his version number to the name of the library file and does not use softlinks to use the name of the library file without the version number. The version number of the library file is not the same on different distributions.
I will fix this by including a specific version of the icu library in the deb package.

Translated with www.DeepL.com/Translator (free version)

**Comment by saturneric** [comment]
I'll just use Ubuntu 22.04 to compile the deb package, as it should be done

**Comment by saturneric** [comment]
Done.
