### ISSUE TITLE
missing Qt libraries, although installed - AppImage could solve this!

### ISSUE THREAD

**Issue by edmundlaugasson** [saturneric/GpgFrontend#7]
The error message under Ubuntu 20.04 LTS, [which is the latest LTS-version](https://wiki.ubuntu.com/Releases) (_Long Term Support_).
`./gpgfrontend: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./gpgfrontend)`

At the same time in same system:
```
ls -lah /lib/x86_64-linux-gnu/|grep -i libQt5Core
-rw-r--r--   1 root root 1.3K Apr  9  2020 libQt5Core.prl
lrwxrwxrwx   1 root root   20 Apr  9  2020 libQt5Core.so -> libQt5Core.so.5.12.8
lrwxrwxrwx   1 root root   20 Apr  9  2020 libQt5Core.so.5 -> libQt5Core.so.5.12.8
lrwxrwxrwx   1 root root   20 Apr  9  2020 libQt5Core.so.5.12 -> libQt5Core.so.5.12.8
-rw-r--r--   1 root root 5.3M Apr  9  2020 libQt5Core.so.5.12.8
```
So, the _qt5-default_ (not _qt-default_ as guided at [readme.md](https://github.com/saturneric/GpgFrontend/blob/main/README.md)) is obviously too old version... Would suggest to search newest version of Qt, e.g. in Debian-based systems:
```
apt-cache search qt|grep default
qt3d-defaultgeometryloader-plugin - Qt 3D default geometry loader plugin
qt5-default - Qt 5 development defaults package
```

Yet another check:
```
file gpgfrontend 
gpgfrontend: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=8bc5bd7e72243f0332b83be64125e154fd92ea1f, for GNU/Linux 3.2.0, not stripped
```

That Qt library version issue could be solved, if [AppImage](https://appimage.org/) version would be available for Linux. Then all dependencies would be included inside container and it can be used also in both: older and newer distros without dependency issues.

Public AppImage repositories:
* [https://www.appimagehub.com/](https://www.appimagehub.com/)
* [https://appimage.github.io/](https://appimage.github.io/apps/)

Then it would be also easier for people to search apps in AppImage format at one place.

There is also [AppImage Launcher](https://github.com/TheAssassin/AppImageLauncher), which makes launching AppImage files and creating appropriate menu item easier.

**Comment by saturneric** [comment]
Thank you for your feedback, I will package and release it in the near future. You can install qt to temporarily solve this problem.
`sudo apt install qt5-default`

**Comment by edmundlaugasson** [comment]
That's what I mentioned - I installed that package, but it's too old, only 5.12, but 5.15 was required and app won't start.

**Comment by saturneric** [comment]
I understand now. I will solve this problem as soon as possible. I will keep this issue open until the problem is solved.
Thanks!

**Comment by edmundlaugasson** [comment]
Great! Same applies also other distros, e.g. Manjaro (based on Arch) is quite popular and I would also switch to Manjaro at some point. There are https://archlinux.org/packages/ for Arch and https://manjaro.org/branch-compare/ for Manjaro (also [this site](https://discover.manjaro.org/applications/), which descriptions seems to be a bit outdated). Arch and its based distros are very up-to-date, there is already Qt6 available. In Manjaro, there is AppImage Launcher installed already by default. I don't even know, what package to install under Manjaro in order to run GPG Frontend app. Is it _qt5-base_ instead of _qt5-default_? Although in Manjaro (also in Arch) is already _qt6-base_ also available. Manjaro is very promising distro, as it has strong community and is rolling release, which makes using computer much more comfortable (no need to install OS again).
There is also [Gentoo Linux packages repository](https://packages.gentoo.org/) and other great distros. I guess AppImage would solve the challenge to run GPG Frontend under different distros.

**Comment by saturneric** [comment]
Thank you for your suggestion, so that this issue can be resolved. You can download the latest released version and double-click to run GpgFrontend.

**Comment by edmundlaugasson** [comment]
Thank you! I hope not only me, but also others will appreciate that.
