### ISSUE TITLE
AppImage special-directories don`t work

### ISSUE THREAD

**Issue by anareksik47** [saturneric/GpgFrontend#72]
Hello, there is .appimage in the release, but it use $HOME directory for .gnupg directory`s locate when I create ./gpg-frontend.home/ directory.
This is usually the case when a old AppimageKit is used.

What is special-directories - https://github.com/AppImage/AppImageKit#special-directories

**Comment by saturneric** [comment]
The AppImage of GpgFrontend is made by [linuxdeployqt](https://github.com/probonopd/linuxdeployqt). Maybe this feature is not supported by linuxdeployqt yet.
