### ISSUE TITLE
Standard Exception Thrown

### ISSUE THREAD

**Issue by anareksik47** [saturneric/GpgFrontend#74]
If I use Russian localization I get Standard Exception Thrown when I try to verify the signature: Standard exception. Not a critical issue. Perhaps the negligence of the programmer. Please notify the developer - this error is described in Russian, so I cannot quote it verbatim.

I checked, these errors do not occur when using English or Ukrainian.

I use last Appimage version, Arch Linux, last kernel.

**Comment by saturneric** [comment]
Thanks for the feedback, this issue has been fixed in the latest version.
