### ISSUE TITLE
"gpg not installed correctly"?

### ISSUE THREAD

**Issue by flippflapp** [saturneric/GpgFrontend#78]
OS: macOS 12.5.1 (21G83)
gpg: 2.3.7_1

------

When starting GPGFrontend, I get the following warning:

> Gnupg(gpg) is not installed correctly, please follow the ReadME instructions in Github to install Gnupg and then open GpgFrontend.

However, I do have the latest gpg installed via brew. Could it be a problem that I use brew on a non-admin account? On my system, brew is installed in `/Users/user/homebrew/bin/gpg` (where "user" is my non-admin user account). Note that I on purpose separate my admin and user account so making my user account admin is not an option.

How can this be solved?:)

**Comment by saturneric** [comment]
It may be a problem on libgpgme. Thanks for discovering this bug. I'll make a plan to work on it in two weeks.

**Comment by Sercurio** [comment]
Up, getting same error same installation of gnupgp via brew and gpgfrontend via the installer

**Comment by saturneric** [comment]
The work is still under way now. This might be an issue on gpgme.

**Comment by saturneric** [comment]
According to the gpgme‘s source code which I have read, can you execute "gpgconf" in the command line?  If not, add "/Users/user/homebrew/bin/" in the PATH, everything might work.

**Comment by Robbepop** [comment]
I just encountered this bug. Just setup a new MacOS, installed homebrew and `gpgfrontend` via `brew install --cask gpgfrontend` but when starting `gpgfrontned` says "`gnupg(gpg)` seems to be installed incorrectly". Not sure what to do since the only thing it does is to recommend installing `gpgfrontend` exactly the way I did.

**Comment by hnykda** [comment]
Still an issue on latest Brew version and Mac OS X Ventura.

**Comment by saturneric** [comment]
In my MacBook, GnuPG binaries are installed by Homebrew at "/usr/local/bin/". This might be the key to the issue.

**Comment by Haarolean** [comment]
> In my MacBook, GnuPG binaries are installed by Homebrew at "/usr/local/bin/". This might be the key to the issue.

It shouldn't, though. `/usr` is not a writable directory in newer MacOS versions anymore, that's why brew installs its packages into `/opt`. Anyway, gpg is present in my path but it still is not recognizable. Also, I tried adjusting the gpg path in settings, setting it to brew's bin directory, but it still doesn't work. Any way to debug this?

**Comment by saturneric** [comment]
> > In my MacBook, GnuPG binaries are installed by Homebrew at "/usr/local/bin/". This might be the key to the issue.
> 
> It shouldn't, though. `/usr` is not a writable directory in newer MacOS versions anymore, that's why brew installs its packages into `/opt`. Anyway, gpg is present in my path but it still is not recognizable. Also, I tried adjusting the gpg path in settings, setting it to brew's bin directory, but it still doesn't work. Any way to debug this?

When the Application starts, GpgME needs to find "gpgconf" in PATH, execute it and get the location of reset GnuPG's executables. If GpgME doesn't get any valid location, GpgFrontend will check out it and notice user that "gpg not installed correctly".

When you execute "gpgconf", it will output like the following (in my MacBook).

```
gpg:OpenPGP:/usr/local/Cellar/gnupg/2.4.0/bin/gpg
gpgsm:S/MIME:/usr/local/Cellar/gnupg/2.4.0/bin/gpgsm
keyboxd:Öffentliche Schlüssel:/usr/local/Cellar/gnupg/2.4.0/libexec/keyboxd
gpg-agent:Geheime Schlüssel:/usr/local/Cellar/gnupg/2.4.0/bin/gpg-agent
scdaemon:Smartcard:/usr/local/Cellar/gnupg/2.4.0/libexec/scdaemon
dirmngr:Netz:/usr/local/Cellar/gnupg/2.4.0/bin/dirmngr
pinentry:Passwort Eingabe:/usr/local/opt/pinentry/bin/pinentry
```

Can you check and paste the "gpgconf" output here?

**Comment by Haarolean** [comment]
Yes, please:

```
% gpgconf
gpg:OpenPGP:/opt/homebrew/Cellar/gnupg/2.3.8/bin/gpg
gpgsm:S/MIME:/opt/homebrew/Cellar/gnupg/2.3.8/bin/gpgsm
keyboxd:Public Keys:/opt/homebrew/Cellar/gnupg/2.3.8/libexec/keyboxd
gpg-agent:Private Keys:/opt/homebrew/Cellar/gnupg/2.3.8/bin/gpg-agent
scdaemon:Smartcards:/opt/homebrew/Cellar/gnupg/2.3.8/libexec/scdaemon
dirmngr:Network:/opt/homebrew/Cellar/gnupg/2.3.8/bin/dirmngr
pinentry:Passphrase Entry:/opt/homebrew/opt/pinentry/bin/pinentry
```

**Comment by hnykda** [comment]
Mine is (Macbook Air M2):

```
$ gpgconf
gpg:OpenPGP:/opt/homebrew/Cellar/gnupg/2.4.0/bin/gpg
gpgsm:S/MIME:/opt/homebrew/Cellar/gnupg/2.4.0/bin/gpgsm
keyboxd:Public Keys:/opt/homebrew/Cellar/gnupg/2.4.0/libexec/keyboxd
gpg-agent:Private Keys:/opt/homebrew/Cellar/gnupg/2.4.0/bin/gpg-agent
scdaemon:Smartcards:/opt/homebrew/Cellar/gnupg/2.4.0/libexec/scdaemon
dirmngr:Network:/opt/homebrew/Cellar/gnupg/2.4.0/bin/dirmngr
pinentry:Passphrase Entry:/opt/homebrew/opt/pinentry/bin/pinentry
```

**Comment by saturneric** [comment]
Guys, I can provide you with a BETA version which may solve this problem after you set the custom GnuPG path. Thought I cannot upgrade my MacBook sadly, can I have you help me to test this version?

**Comment by hnykda** [comment]
I can try!

**Comment by saturneric** [comment]
You can download [HERE](https://file.io/isZOCvCxryBa). 

When GpgFrontend can't find `gpgconf`, you can see this Dialog. 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/20257134/230023282-e25f3bc0-ac31-4886-b76a-d3039189ff05.png">

Click open and select a custom GnuPG path. For your MacBook, it may be `/opt/homebrew/bin/`.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/20257134/230023765-f36bde05-5153-4023-a44e-155c9663890a.png">

**Comment by saturneric** [comment]
@hnykda, You can download it [HERE](https://file.io/sfF8G6dMTGNm).

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/230212581-695903d3-00d7-4ea0-a3e3-83e2b2936f14.png)

Seems to be working, thanks!

**Comment by Haarolean** [comment]
@saturneric can I get one as well? The link you shared has expired.
