### ISSUE TITLE
无法创建 ECDH 密钥，以及 Win 平台 便携化的问题。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [saturneric/GpgFrontend#79]
平台：Win11 22H2 
版本： 2.0.9-windows-x86_64-protable

### 发现两个问题。
1. 无法 创建 ECDH 密钥，当然可以导入
2.  设置中，信息面板 中，字体大小设置无效，且每次自动变为10.

### 关于软件便携化的一些建议。
由于 win 平台的安全性和软件配置管理的需求。
希望能实现 GpgFrontend 和 GPG 配置目录的集中管理，
两个软件的所有配置集中在一个指定的目录中。
理想状态是通过  GpgFrontend 启动参数 或者在软件根目录的配置，来指定配置目录。

对于后台的 GPG 服务，希望能由 GpgFrontend ，进行管理，比如跟随启动和关闭等。
用户最好能设定启动和关闭的参数。

最后感谢开发者。
让Win平台终于有个好用的GPG前端了💐🎊🎉

**Comment by saturneric** [comment]
感谢反馈！我会在这两周之内适配ECDH ，字体大小设置问题已经在develop分支中得到了解决。新的版本可能在这两周之内发布。
GnuPG的配置和控制问题是一个比较大的问题。据我目前所知的，libgpgme在当前版本没有提供完善的支持。如果想要引入，则需要直接对GnuPG进行操作。这一块可能会在后续版本中考虑引入，取决于用户对这个功能的呼声高不高。

**Comment by saturneric** [comment]
[e43307b](https://github.com/saturneric/GpgFrontend/commit/e43307bb53ca02a67b70a8b36a0d237ac55b7e16) 已添加ECC密钥支持
