### ISSUE TITLE
AppImage integration with system via AppImageLauncher

### ISSUE THREAD

**Issue by edmundlaugasson** [saturneric/GpgFrontend#8]
Hereby I propose to improve AppImage version of GpgFrontend to allow integrate it with system using [AppImage Launcher](https://github.com/TheAssassin/AppImageLauncher). This has two core features: 
* creating appropriate ~/.local/share/applications/*.desktop for easy running the app from main menu by making AppImage file automatically also executable - all this happens graphically and automatically.
* allowing to update the app
This improvement would complete the AppImage transition. Once the AppImage file is downloaded, right-click on that and open with AppImage Launcher would do the trick.

**Comment by saturneric** [comment]
Thanks, I will test it in few days.

**Comment by saturneric** [comment]
I use latest [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to package the GpgFrontend. Is GpgFrontend unable to use AppImage Launcher because of this tool?

**Comment by edmundlaugasson** [comment]
Sorry, but I am not developer. I know these apps,also use them but that's all.
If you check, e.g. 
`gpgfrontend-x86_64.AppImage --appimage-updateinformation`
...then you should see something like
`gh-releases-zsync|AppImage|AppImageUpdate|continuous|gpgfrontend-*x86_64.AppImage.zsync`
...but currently there is only a message:
`qt5ct: using qt5ct plugin`
Also appropriate ~/.local/share/applications/*.desktop file was also not created to make app easily to open via main menu. How to achieve these, haven't investigated.
There might be needed also refresh main menu to make recently added apps visible in main menu - I've tried to investigate that command at CLI, not yet successful. Making *.desktop file trusted (that direct CLI command I know), executable does not help. If you find it, would be great if you can share here.

**Comment by saturneric** [comment]
I have understood this problem and it needs to be improved. I expect to deal with this issue in a few days.

**Comment by saturneric** [comment]
Hello, after my test, GpgFrontend can be opened and integrated with AppImageLuancher.
I tested it on ubuntu 16.04.
