### ISSUE TITLE
Pre-release v2.0.10 : KeyPair Manager columns

### ISSUE THREAD

**Issue by Achim16** [saturneric/GpgFrontend#88]
Can I suggest an enhancement to the KeyPair Manager 

I would be good if there were columns displaying the key creation date, algorithm and key size in the key list. 

Maybe in a menu allowing the user to select columns he want to see

Thank you for your great work

**Comment by saturneric** [comment]
c9d687d308ee7e64684892435e4ef832ed6f9923 function added.
