### ISSUE TITLE
[Enhancement] Please add/create a Formula or Cask for Homebrew

### ISSUE THREAD

**Issue by orgcontrib** [saturneric/GpgFrontend#89]
This would help grow the project's popularity while making more users happy.

- [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook)
- [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook)

**Comment by saturneric** [comment]
Okay, this reminds me. It's on my plan now.

**Comment by saturneric** [comment]
Done. You'all can see here.
https://github.com/Homebrew/homebrew-cask/commit/5f2f2dfcc77e7df687feb0fbd34ba6c0d3fef162

I'll update README soon.
