### ISSUE TITLE
Export Private Key

### ISSUE THREAD

**Issue by AliRezaBeigy** [saturneric/GpgFrontend#9]
Hello
I hope you are well

I was generating a key with GpgFrontend after that I'm was going to export the private key, after click on the "OK" button and select the destination, it was export public key

can you check this issue?

**Comment by saturneric** [comment]
Okay, I will check the problem.

**Comment by saturneric** [comment]
Hello, this bug fixed at commit 0de1cf66d45bae6a781584c1ab4d9d59bc04bc6e. You can download v1.0.8 to use this function properly.
