### ISSUE TITLE
Export ALL private and public-only keys in a single package

### ISSUE THREAD

**Issue by RealCr4ckhead** [saturneric/GpgFrontend#90]
Hello,

it came to my attention that GPG Frontend can't export all private and public-only keys in a single package. Would it be possible to implement such feature? It would simplify the process of importing all keys to a live OS.

Currently, it only exports one or the other, resulting in two packages having to export/import, gets annoying real fast if you have to do it multiple times a day.

Thank you a lot!

**Comment by saturneric** [comment]
The problem, described above, is actually a functional mistake and I have solved it. This fixture will be released at v2.0.11.

**Comment by RealCr4ckhead** [comment]
Thank you, appreciate your work.

**Comment by RealCr4ckhead** [comment]
Sorry for bothering you, are there any plans on releasing 2.0.11 any time soon, maybe in a few days? Thank you.

**Comment by saturneric** [comment]
Still, many works should be done, but haven't done yet. But I can send you a pre-release that I am debugging now.  Download as quick as possible, or this link will expire soon. Get it from [HERE](https://gofile.io/d/SMmQck).

**Comment by RealCr4ckhead** [comment]
Apologies, I should've specified I needed the Linux (Debian) version, this seems like a Windows version, could you, please, send me the Linux one? Thank you so much.

**Comment by saturneric** [comment]
Okay, wait for me.

**Comment by saturneric** [comment]
[HERE](https://gofile.io/d/NH9acd) is what you want.
