### ISSUE TITLE
Windows Portable version typo

### ISSUE THREAD

**Issue by jgonyea** [saturneric/GpgFrontend#92]
The releases have a typo in the name for the portable version (protable vs portable).

**Comment by saturneric** [comment]
Thanks.

**Comment by sergeevabc** [comment]
The transition to QT6 cut off Windows 7 users. What a move, folks. For the sake of the shiny buttons, you sacrificed the safety of people who don't care about Microsoft [planned obsolescence](https://en.wikipedia.org/wiki/Planned_obsolescence). Thank goodness your hall-of-shame example isn't followed by security solutions for the masses like [Keepass](https://keepass.info/), [Age](https://github.com/FiloSottile/age), and even [GPG](https://gpg4win.org/system-requirements.html) itself. I wonder how apps such as [CrowTranslate](https://crow-translate.github.io/), [DB Browser for SQLite](https://sqlitebrowser.org/), [OcenAudio](https://www.ocenaudio.com/) get by with QT5?

**Comment by saturneric** [comment]
> The transition to QT6 cut off Windows 7 users. What a move, folks. For the sake of the shiny buttons, you sacrificed the safety of people who don't care about Microsoft [planned obsolescence](https://en.wikipedia.org/wiki/Planned_obsolescence). Thank goodness your hall-of-shame example isn't followed by security solutions for the masses like [Keepass](https://keepass.info/), [Age](https://github.com/FiloSottile/age), and even [GPG](https://gpg4win.org/system-requirements.html) itself. I wonder how apps such as [CrowTranslate](https://crow-translate.github.io/), [DB Browser for SQLite](https://sqlitebrowser.org/), [OcenAudio](https://www.ocenaudio.com/) get by with QT5?

Thank you for sharing your concerns regarding the transition to Qt6 and its impact on Windows 7 users. I understand your frustration and the importance of ensuring that software remains accessible and secure for all users, regardless of their operating system. Your point about the significance of maintaining support for essential security solutions like KeePass, Age, and GPG is particularly well-taken. It highlights the need for a balanced approach between adopting new technologies and preserving compatibility.

In light of your feedback, I am considering the release of a special version compiled with Qt5 for versions 2.1.2 and later, to accommodate users on older systems. Additionally, the use of OpenSSL 1.1.1 will be maintained to ensure continued security. Your input is invaluable, and I am committed to finding a solution that respects the needs of all users. Thank you for bringing this to my attention.
