### ISSUE TITLE
Unable to verify signature with file name in Chinese

### ISSUE THREAD

**Issue by wind-mask** [saturneric/GpgFrontend#97]
I found that for the file name in Chinese, it cannot be verified after signing.
![2023-04-10_221702](https://user-images.githubusercontent.com/110806349/230919441-3d2dd623-e30e-4000-89b6-8e38b04d9588.png)
![2023-04-10_221719](https://user-images.githubusercontent.com/110806349/230919476-f7807aa8-c93b-463b-a3f8-299277ccbf19.png)
![2023-04-10_221759](https://user-images.githubusercontent.com/110806349/230919504-a47696a1-d4b2-4122-b023-370dad5eb726.png)

**Comment by saturneric** [comment]
I have tested this case using version 2.1.1 and everything appears to be in order. If you encounter this problem again, feel free to reopen this issue.
